dist: trusty
sudo: false
language: python
script: python -m unittest
deploy:
  provider: pypi
  skip_cleanup: true
  user: Secbone
  password:
    secure: X08VNVcjrX1BjMIX30MAta4oGWqaf+9Qx8g2knBt1hIwZS9MtiuCHDz0E5LMhqCn/t07iE82qx7nnN50YXOeXk5hK0HJ0CF5S6ylFaIALspTLvJyRxgc9MQVspr7QYvXFQS71Z9QnrWUJtTNINB6lta+lDxkgMaJeVu/9YW5EvJBKcOKxDfK0F2jFEF9PWh0u3nlJlbAirAARCW7125vkvHKbw76dj2Ub/3ZR1v613edjJ2ScdBoCrGHCh5cnv4C5UPnPfKhwGLzqog6QoF7Uq9m6csGNErsCAEY5lq1Bhw9NhCBBeZEnLAGrg9QSL4Mv1wZYMV1gxYQwxA0XTHDjkPPRBLdxryVgeba3ueaMkUu5TjqnUem1D0JTE596MTxGOGGIOykK3ikCyZfHpStGVHwT7kc0nJ+YxjIUiNA6Yn7vsukP6BUm1iFMwkNAYIOFdBsJ6n/o3Qc6sH8LbbOkAa9oSynRIApiJf/N0T9jqTn1bW3ZopESbbgGcguKq4kWYAtcqH0YFdynml2/Ag1WN5sz8s5YvjRxtszgoPLgw+bTmyQLJ6yrmNyPJeqtyn8nti9WljWvMapr2hckhbWonTMCS6eRPmx+H7O9ywoul7NEKM6PXYJjxOch3A63KSjQM8sEg/x899UWNLbTT23ZjHjC6uv71whKKnTQYhjxjg=
  on:
    tags: true
    repo: Secbone/py_publish_test
