matrix:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      language: python
      python: "3.6"
      sudo: false
      before_install:
          - sudo apt-get install -y graphviz
      dist: trusty
      before_deploy:
          - make dist
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
          - brew install python3 graphviz
      before_deploy:
          - make dist_wheel
    - name: "Python 3.7.3 on Windows"
      os: windows
      language: sh
      python: "3.7"
      before_install:
          - choco install python3
          - choco install graphviz
          - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
          - python3 -m pip install --upgrade pip wheel setuptools twine
  allow_failures:
    - os: windows

install:
    - pip3 install pandas pytest
script: make test

deploy:
  skip_cleanup: true
  provider: script
  script:
      - make upload
  on:
    tags: true
    repo: Secbone/py_publish_test
