name: Unit Test

on: push

strategy:
  matrix:
    platform: [ubuntu-latest, macos-latest, windows-latest]
    python-version: ['3.6', '3.7', '3.8']
  fail-fast: false

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: Test py ${{ matrix.python-version }} on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: make test
      - run: make dist_wheel
      - uses: pypa/gh-action-pypi-publish@master
        name: publish pypi
        with:
          user: __token__
          password: ${{ secrets.pypi }}
