name: Unit Test

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8']
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    name: Test py ${{ matrix.python-version }} on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: make test
      - run: make dist_wheel
      - uses: RalfG/python-wheels-manylinux-build@v0.2.2
        if: matrix.platform == 'ubuntu-latest'
        build-requirements: 'cython numpy'
      - uses: pypa/gh-action-pypi-publish@master
        name: publish pypi
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
          repository_url: https://test.pypi.org/legacy/
