name: Unit Test

on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8']
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    name: Test py ${{ matrix.python-version }} on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: make test
      - run: make dist_wheel
      - uses: actions/upload-artifact@v2  
        with:
          name: wheel
          path: dist/*.whl
  release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        with:
          name: wheel
          path: dist/
      - uses: RalfG/python-wheels-manylinux-build@v0.2.2
        with:
          build-requirements: 'cython numpy'
      - uses: pypa/gh-action-pypi-publish@master
        name: publish pypi
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
          repository_url: https://test.pypi.org/legacy/
